theme: jekyll-theme-modernist
markdown: kramdown
title: CCiC8 - Conference of China iGEMer Community
url: https://coronin.github.io/ccic8

plugins:
  - jekyll-redirect-from

collections:
  posts:
    output: true
    permalink: /:title/
  volunteers:
    output: true
    permalink: /:title
